# Generated by Django 5.0.6 on 2024-07-04 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=14)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
