# Generated by Django 5.0.6 on 2024-07-04 21:57

import datetime
import validators.date_is_past_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0003_gathering_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='birth_date',
            field=models.DateField(default=datetime.date.today, validators=[validators.date_is_past_validator.date_is_past]),
        ),
        migrations.AlterField(
            model_name='baby',
            name='code',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
